/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("io.rest-assured:rest-assured:5.5.1")
    testImplementation("org.testng:testng:7.9.0")
    implementation("com.google.code.gson:gson:2.10.1")
    testImplementation("org.assertj:assertj-core:3.26.0")
    testImplementation("io.rest-assured:json-schema-validator:5.5.1")
}

tasks.test {
    useTestNG {
        if(System.getProperty("RunSmokeTest","false").equals("true")) {
            suites("/src/test/resources/TestSuites/SmokeSuite.xml")
        }
        if(System.getProperty("RunSlowTests","false").equals("true")) {
            suites("/src/test/resources/TestSuites/SlowTests.xml")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

